version: '3.8'

services:
  backend:
    build:
      context: ./DiffPack
      dockerfile: Dockerfile
    ports:
      - "44319:80"

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    environment:
      - BACKEND_URL="http://backend:80"
    depends_on:
      - backend
    ports:
      - "5173:80"
